<%@ Page Title="" Language="C#" MasterPageFile="~/admin/MasterPage.master" AutoEventWireup="true" CodeFile="admissions.aspx.cs" Inherits="admin_admissionlist" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
    <form id="form1" runat="server">
    <link rel="stylesheet" href="/style2.css" />
    <h1>Admissions</h1><br /><br />
    <center><a href="newadmission.aspx">New Admission</a><br /><br /></center><br />

<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" HeaderStyle-CssClass="h" RowStyle-CssClass="r" BorderStyle="Solid" BorderColor="Black" AutoGenerateDeleteButton="True">
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
        <asp:BoundField DataField="fnm" HeaderText="First Name" SortExpression="fnm" />
        <asp:BoundField DataField="lnm" HeaderText="Last Name" SortExpression="lnm" />
        <asp:BoundField DataField="fathernm" HeaderText="Father's Name" SortExpression="fathernm" />
        <asp:BoundField DataField="dob" HeaderText="DOB" SortExpression="dob" />
        <asp:BoundField DataField="gender" HeaderText="Gender" SortExpression="gender" />
        <asp:BoundField DataField="adhaarno" HeaderText="Adhaar No." SortExpression="adhaarno" />

        <asp:TemplateField HeaderText="Photo">
            <ItemTemplate>
                <asp:Image ID="photo" runat="server" ImageUrl='<%# "/images/" + Eval("photo") %>' />
            </ItemTemplate>
            <ControlStyle Height="100px" Width="100px" />
        </asp:TemplateField>

        <asp:BoundField DataField="parentprof" HeaderText="Parent's Profession" SortExpression="parentprof" />
        <asp:BoundField DataField="codept" HeaderText="Co./Dept. Name" SortExpression="codept" />
        <asp:BoundField DataField="designation" HeaderText="Designation" SortExpression="designation" />
        <asp:BoundField DataField="address" HeaderText="Address" SortExpression="address" />
        <asp:BoundField DataField="whatsappno" HeaderText="Whatsapp No." SortExpression="whatsappno" />
        <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" />
        <asp:BoundField DataField="studmno" HeaderText="Student's Mobile No." SortExpression="studmno" />
        <asp:BoundField DataField="pmno" HeaderText="Parent's Mobile No." SortExpression="pmno" />
        <asp:BoundField DataField="lastexam" HeaderText="Last Appeared/Passed Exam" SortExpression="lastexam" />
        <asp:BoundField DataField="yrofpassing" HeaderText="Year Of Passing" SortExpression="yrofpassing" />
        <asp:BoundField DataField="instnm" HeaderText="Institute Name" SortExpression="instnm" />
        <asp:BoundField DataField="pr" HeaderText="Percentage" SortExpression="pr" />
        <asp:BoundField DataField="std" HeaderText="Standard" SortExpression="std" />
        <asp:BoundField DataField="schoolnm" HeaderText="School Name" SortExpression="schoolnm" />
        <asp:BoundField DataField="course" HeaderText="Course" SortExpression="course" />
        <asp:BoundField DataField="sem" HeaderText="Semester" SortExpression="sem" />
        <asp:BoundField DataField="collegenm" HeaderText="College Name" SortExpression="collegenm" />
        <asp:BoundField DataField="othercourse" HeaderText="Other Course" SortExpression="othercourse" />
        <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" />
        <asp:HyperLinkField HeaderText="Confirm" Text="Confirm" DataNavigateUrlFields="id" DataNavigateUrlFormatString="confirmad.aspx?id={0}" />
    </Columns>

<HeaderStyle CssClass="h"></HeaderStyle>

<RowStyle CssClass="r"></RowStyle>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:cn %>" SelectCommand="SELECT * FROM [admission]" DeleteCommand="DELETE FROM [admission] WHERE [id] = @id"></asp:SqlDataSource>
    </form>
</body>
</html>

</asp:Content>



