<%@ Page Title="" Language="C#" MasterPageFile="~/admin/MasterPage.master" AutoEventWireup="true" CodeFile="pdf.aspx.cs" Inherits="admin_pdf" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <form id="form1" runat="server">
    
    <link rel="stylesheet" href="/style2.css" />

    <h1>PDF</h1><br /><br />
    

    <asp:Table ID="Table1" runat="server" CellPadding="6" HorizontalAlign="Center" BackColor="#CCCCFF" HeaderStyle-CssClass="h" RowStyle-CssClass="r" BorderStyle="Solid" BorderColor="Black">
    <asp:TableRow>
        <asp:TableCell><b>Course</b></asp:TableCell>
        <asp:TableCell>
            <asp:DropDownList ID="course" runat="server" Width="175px" Height="23">
            <asp:ListItem Text="--select--" Value="" />
            <asp:ListItem Text="BCA" /><asp:ListItem Text="MCA" />
            </asp:DropDownList>
        </asp:TableCell>
    </asp:TableRow>

    <asp:TableRow>
        <asp:TableCell><b>Semester</b></asp:TableCell>
        <asp:TableCell><asp:DropDownList ID="sem" runat="server" Width="175px" Height="23">
            <asp:ListItem Text="--select--" Value="" />
            <asp:ListItem Text="Sem-1" /><asp:ListItem Text="Sem-2" /><asp:ListItem Text="Sem-3" />
            <asp:ListItem Text="Sem-4" /><asp:ListItem Text="Sem-5" /><asp:ListItem Text="Sem-6" />
            </asp:DropDownList></asp:TableCell>
    </asp:TableRow>

    <asp:TableRow>
        <asp:TableCell><b>Subject</b></asp:TableCell>
        <asp:TableCell><asp:TextBox ID="subject" runat="server" /></asp:TableCell></asp:TableRow><asp:TableRow>
        <asp:TableCell><b>Upload File</b></asp:TableCell><asp:TableCell><asp:FileUpload ID="fileUpload" runat="server" /></asp:TableCell>
    </asp:TableRow>

    <asp:TableRow>
        <asp:TableCell></asp:TableCell><asp:TableCell><asp:Button ID="upload" runat="server" Text="Upload" OnClick="btnUpload_Click" BackColor="#006393" ForeColor="White" Font-Size="Medium" Height="30px" /></asp:TableCell>
    </asp:TableRow>

    </asp:Table><br /><br />
    

        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" CellPadding="10" Width="100%" HeaderStyle-CssClass="h" RowStyle-CssClass="r">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="course" HeaderText="Course" SortExpression="course" />
                <asp:BoundField DataField="sem" HeaderText="Semester" SortExpression="sem" />
                <asp:BoundField DataField="subject" HeaderText="Subject" SortExpression="subject" />
                <asp:BoundField DataField="pdf" HeaderText="Pdf" SortExpression="pdf" />
                <asp:BoundField DataField="path" HeaderText="Path" SortExpression="path" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:cn %>" SelectCommand="SELECT * FROM [pdf]" DeleteCommand="DELETE FROM [pdf] WHERE [id] = @id"></asp:SqlDataSource></form>
</asp:Content>

