<%@ Page Title="" Language="C#" MasterPageFile="~/admin/MasterPage.master" AutoEventWireup="true" CodeFile="users.aspx.cs" Inherits="admin_userlist" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>

    <form id="form1" runat="server">
    <link rel="stylesheet" href="/style2.css" />

    <h1>Users</h1>

        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" CellPadding="10" Width="100%" AutoGenerateDeleteButton="True" DataKeyNames="mno" HeaderStyle-CssClass="h" RowStyle-CssClass="r">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="Id" SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" />
                <asp:BoundField DataField="mno" HeaderText="Mobile No." SortExpression="mobile" />
                <asp:BoundField DataField="usertype" HeaderText="Usertype" SortExpression="usertype" />
            </Columns>

<HeaderStyle CssClass="h"></HeaderStyle>

<RowStyle CssClass="r"></RowStyle>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:cn %>" SelectCommand="SELECT [id], [name], [email], [mno], [usertype] FROM [user_login]" DeleteCommand="DELETE FROM [user_login] WHERE [mno] = @mno"></asp:SqlDataSource>
    </form>
</body>
</html>
</asp:Content>

